---
- name: Install and start Apache webserver.
  hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: Install apache webserver package.
      yum:
        name: httpd
        state: present

    - name: Copy webcontent (index.html) to webservers.
      template:
        src: index.html.j2
        dest: /var/www/html/index.html

    - name: Start apache webserver
      service:
        name: httpd
        state: started
        enabled: true

    - name: Open HTTP service in firewall.
      firewalld:
        service: http
        state: enabled
