---
- name: Test webserver
  hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: Testing webserver output
      uri:
        url: http://{{ ansible_facts.default_ipv4.address }}
      register: webserver_output
      
    - name: output validation
      debug:
        var: webserver_output
